FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml* package-lock.json* ./
COPY scripts ./scripts/
RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 6006

CMD ["sh", "-c", "npx storybook dev -p 6006 --ci --host 0.0.0.0 & npm run dev"]
